apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victorswed/cellit.git
    targetRevision: HEAD
    path: infra/apps/argo-events
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true  # You probably don’t want to prune sub-apps here
      selfHeal: true
