apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/victorswed/cellit.git
    targetRevision: main
    path: apps/devhub/charts/devhub
    helm:
      releaseName: devhub
  destination:
    server: https://kubernetes.default.svc
    namespace: devhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

