apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://flagger.app
    chart: flagger
    targetRevision: 1.37.0
    helm:
      releaseName: flagger
      values: |
        # Enable Istio integration
        meshProvider: istio
        # Flagger will watch for canary objects in all namespaces
        namespace: ""
        # Enable the loadtester (required for webhooks)
        loadtester:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: flagger-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true