apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-routes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victorswed/cellit.git
    targetRevision: main
    path: "infra/istio"
    helm:
      values: |
        gateway:
          name: ingress-gw
          namespace: istio-system
          selector:
            istio: ingressgateway
          port: 80
          hosts:
            - "*.dev.localhost"

        virtualServices:
          - name: argocd-vs
            namespace: istio-system
            gateway: ingress-gw
            hosts: 
              - "argocd.dev.localhost"
            http:
              - match:
                - uri:
                    prefix: /
                route:
                  - destination:
                      host: argocd-server.argocd.svc.cluster.local
                      port: 
                        number: 80
          - name: argoworkflows-vs
            namespace: istio-system
            gateway: ingress-gw
            hosts: 
              - "argoworkflows.dev.localhost"
            http:
              - match:
                - uri:
                    prefix: /
                route:
                  - destination:
                      host: argo-workflows-server.argo-workflows.svc.cluster.local
                      port: 
                        number: 2746
          - name: argoevents-vs
            namespace: istio-system
            gateway: ingress-gw
            hosts: 
              - "argoevents.dev.localhost"
            http:
              - match:
                - uri:
                    prefix: /
                route:
                  - destination:
                      host: webhook-eventsource-svc.argo-events.svc.cluster.local
                      port: 
                        number: 12000
          - name: devhub-vs
            namespace: istio-system
            gateway: ingress-gw
            hosts:
              - "devhub.dev.localhost"
            http:
              - name: backend-api
                match:
                  - uri:
                      prefix: /api
                route:
                  - destination:
                      host: devhub-devhub-backend.devhub.svc.cluster.local
                      port:
                        number: 8000
              - name: frontend-route
                match:
                  - uri:
                      prefix: /
                route:
                  - destination:
                      host: devhub-devhub-frontend.devhub.svc.cluster.local
                      port:
                        number: 80
                    weight: 100
                  - destination:
                      host: devhub-devhub-frontend-canary.devhub.svc.cluster.local
                      port:
                        number: 80
                    weight: 0
          - name: argorollouts-vs
            namespace: istio-system
            gateway: ingress-gw
            hosts: 
              - "argo-rollouts.dev.localhost"
            http:
              - match:
                - uri:
                    prefix: /
                route:
                  - destination:
                      host: argo-rollouts-dashboard.argo-rollouts.svc.cluster.local
                      port: 
                        number: 3100                
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true