apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 13.6.2  # You can check the latest stable
    helm:
      releaseName: mongodb
      values: |
        auth:
          rootUser: root
          rootPassword: root
        architecture: replicaset
        replicaCount: 1
        persistence:
          enabled: true
          size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
