apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 13.6.2
    helm:
      releaseName: mongodb
      values: |
        architecture: standalone
        auth:
          enabled: true
          rootUser: root
          rootPassword: root
        persistence:
          enabled: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        podSecurityContext:
          enabled: false
        containerSecurityContext:
          enabled: false
        # More generous probes for local clusters to avoid 5s timeouts
        livenessProbe:
          enabled: true
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          enabled: true
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 18
          successThreshold: 1
        startupProbe:
          enabled: true
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 60
          successThreshold: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mongodb
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://charts.bitnami.com/bitnami
#     chart: mongodb
#     targetRevision: 13.6.2  # You can check the latest stable
#     helm:
#       releaseName: mongodb
#       values: |
#         auth:
#           rootUser: root
#           rootPassword: root
#         architecture: replicaset
#         replicaCount: 1
#         persistence:
#           enabled: true
#           size: 1Gi
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: mongodb
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
