    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sealed-secrets
      namespace: argocd
    spec:
      project: default # Or your desired project
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.17.3
        chart: sealed-secrets
      destination:
        server: https://kubernetes.default.svc
        namespace: sealed-secrets # Or your desired namespace for Sealed Secrets controller#   destination:
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true