{{- if eq .Values.frontend.strategy "rollout" }}
# Stable service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devhub.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
---
# Canary service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devhub.fullname" . }}-frontend-canary
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
{{- else }}
# Standard service for deployment mode
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devhub.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devhub.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
data:
  config.js: |
    // Frontend JavaScript runs in browser, must use external endpoints
    window.API_BASE = window.API_BASE || "/api"
    {{- if eq .Values.backend.strategy "rollout" }}
    window.CANARY_ENABLED = true;
    {{- else }}
    window.CANARY_ENABLED = false;
    {{- end }}