{{- if eq .Values.frontend.strategy "rollout" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "devhub.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devhub.name" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devhub.name" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config
          configMap:
            name: {{ include "devhub.fullname" . }}-frontend-config
  strategy:
    canary:
      canaryService: {{ include "devhub.fullname" . }}-frontend-canary
      stableService: {{ include "devhub.fullname" . }}-frontend
      trafficRouting:
        istio:
          virtualService:
            name: devhub-vs.istio-system
            routes: 
              - frontend-route
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 50
        - pause: { duration: 2m }
        - setWeight: 100
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devhub.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devhub.name" . }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devhub.name" . }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config
          configMap:
            name: {{ include "devhub.fullname" . }}-frontend-config
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devhub.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devhub.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "devhub.name" . }}
    app.kubernetes.io/component: frontend
data:
  config.js: |
    window.API_BASE = window.API_BASE || "/api"
