apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.21 # or 'latest' — check https://artifacthub.io/packages/helm/argo/argo-rollouts
    helm:
      releaseName: argo-workflows
      values: |
        server:
          authModes:
            - server 
        artifactRepository:
          s3:
            endpoint: argo-artifacts:9000
            bucket: argo-artifacts
            insecure: true
            accessKeySecret:
              name: argo-artifacts
              key: root-user
            secretKeySecret:
              name: argo-artifacts
              key: root-password
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true