apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcreds
  namespace: sealed-secrets
spec:
  encryptedData:
    .dockerconfigjson: AgDc+jWVJYqlOhgVbrRHkNSYrVkv3r9CuBbs9+f8/OwCT/RPW2eAuqXtAwn1bH0l2jPvy5ypvEuQg8o70NHFiM9WjnthLaA8a4m7WR6v7QDKYOKYpAH9MdbPNbLrj6PCHfhIJpPIoi+I37JUqkaIKox1igFJWwYZWuciAz6rQptbHTNtY/V8uwTgo9/EpJs6C18LvXi2AhWzI6YzdPjO03XDWteyXlS3eIfIX9Di9aBPLiIbRqaSemNlUCGOI15Sc6W6qz6HLC2euM4w1WBYpZZqwIuUfLvhWrMCCcznUdvotpEH4ZU1ClPV/cCyLBgm71exlW3b4GzUqkZuJEqdfx/I5wlXYvz+HL5Wm8XZH1K7eifVzgVLYFFkZrRicsPf0lZlGmXB83eCYPPoWjYdpKgUFJW6HUrNN4QiGJWNa+4VpylvnWHGcdCILuTSkB90oCFxLzoiLbfhb9cZQtI6RObsv7hlWnqckSUDIh8j5vKT6F7sKHhOxt65N8f+JydYUqu1an6V8D16BdiQx79P4WgZMjRogskGocyNB38tYOJJiozAabel3w7mhllBDMr05OfZcH2pg9ZnrFvOJFGsONcbPtBJ6kEIPkyaZoQ2qIO6rINVIrcjUpuAk6fdjiaAdsw5fymJURAsq50JfoloaFHbp0ZJHGekAiefu9V2IFUuonGlLWR2pgifMFj3l9pOlraeNbh42hCmMjLDmGHnAnbxx5hDRZ1ZZ7ocLb9X0/XICuqC3snjgIYEJm9hQ95x1vmZYoHNo17ZDxrSIDUPOyjRzAMxE7cbSjLSL5lbgICFOXNcELeNVQ4bykXf6dA8X7aFK18KKp9Ts9Tqmh4fP5Xm3WJnmXdXjrbU7ssxp7ty9T2WVOeslmFvgsia3ZiTCvDnwmQo/N+WlH8r8Ue+FpZxdoWMTL85XnqcuBlV08N/FczTRHhrz29vFNt/8tuljrgGOLH1rK46
  template:
    metadata:
      name: regcreds
      namespace: argo-workflows
    type: kubernetes.io/dockerconfigjson