apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-ci-pipeline
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows
  entrypoint: main
  ttlStrategy:
    secondsAfterCompletion: 300
  arguments:
    parameters:
      - name: repoUrl
      - name: imageName
      - name: imageTag
      - name: dockerfile
  templates:
    - name: main
      steps:
        - - name: clone
            template: clone-repo
        - - name: lint
            template: lint-dockerfile
            arguments:
              artifacts:
                - name: cloned-repo
                  from: "{{steps.clone.outputs.artifacts.cloned-repo}}"
        - - name: build-and-push
            template: build-and-push-image
            arguments:
              artifacts:
                - name: cloned-repo
                  from: "{{steps.clone.outputs.artifacts.cloned-repo}}"

    - name: clone-repo
      script:
        image: alpine/git
        command: ["sh"]
        source: |
          set -eux
          git clone "{{workflow.parameters.repoUrl}}" /src
        outputs:
          artifacts:
            - name: cloned-repo
              path: /src

    - name: lint-dockerfile
      container:
        image: hadolint/hadolint
        command: ["hadolint"]
        args: ["/src/{{workflow.parameters.dockerfile}}"]
      inputs:
        artifacts:
          - name: cloned-repo
            path: /src

    - name: build-and-push-image
      container:
        image: gcr.io/kaniko-project/executor:latest
        command:
          - /kaniko/executor
        args:
          - --dockerfile=/src/{{workflow.parameters.dockerfile}}
          - --context=/src
          - --destination={{workflow.parameters.imageName}}:{{workflow.parameters.imageTag}}
          - --cache=true
      inputs:
        artifacts:
          - name: cloned-repo
            path: /src
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/

  volumes:
    - name: docker-config
      secret:
        secretName: regcreds
        items:
          - key: .dockerconfigjson
            path: config.json
