apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-ci-pipeline
  namespace: argo-workflows
spec:
  serviceAccountName: argo-workflows
  entrypoint: main
  ttlStrategy:
    secondsAfterCompletion: 300
  arguments:
    parameters:
      - name: repoUrl
      - name: imageName
      - name: imageTag
      - name: dockerfile
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone-repo
            arguments:
              parameters:
                - name: repoUrl
                  value: "{{workflow.parameters.repoUrl}}"

          - name: lint
            template: lint-dockerfile
            dependencies: [clone]
            arguments:
              artifacts:
                - name: cloned-repo
                  from: "{{tasks.clone.outputs.artifacts.cloned-repo}}"
              parameters:
                - name: dockerfile
                  value: "{{workflow.parameters.dockerfile}}"

          - name: build-and-push
            template: build-and-push-image
            dependencies: [clone]
            arguments:
              artifacts:
                - name: cloned-repo
                  from: "{{tasks.clone.outputs.artifacts.cloned-repo}}"
              parameters:
                - name: dockerfile
                  value: "{{workflow.parameters.dockerfile}}"
                - name: imageName
                  value: "{{workflow.parameters.imageName}}"
                - name: imageTag
                  value: "{{workflow.parameters.imageTag}}"

    - name: clone-repo
      inputs:
        parameters:
          - name: repoUrl
      script:
        image: alpine/git
        command: ["sh"]
        source: |
          set -eux
          git clone "{{inputs.parameters.repoUrl}}" /src
          ls -al /src
        outputs:
          artifacts:
            - name: cloned-repo
              path: /src

    - name: lint-dockerfile
      inputs:
        artifacts:
          - name: cloned-repo
            path: /src
        parameters:
          - name: dockerfile
      container:
        image: hadolint/hadolint
        command: ["hadolint"]
        args: ["/src/{{inputs.parameters.dockerfile}}"]

    - name: build-and-push-image
      inputs:
        artifacts:
          - name: cloned-repo
            path: /src
        parameters:
          - name: dockerfile
          - name: imageName
          - name: imageTag
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=/src/{{inputs.parameters.dockerfile}}
          - --context=/src
          - --destination={{inputs.parameters.imageName}}:{{inputs.parameters.imageTag}}
          - --cache=true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/

  volumes:
    - name: docker-config
      secret:
        secretName: regcreds
        items:
          - key: .dockerconfigjson
            path: config.json
