apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.74.0
    helm:
      releaseName: otel
      values: |
        mode: deployment
        config:
          receivers:
            prometheus:
              config:
                scrape_configs:
                  - job_name: 'kubernetes-nodes'
                    kubernetes_sd_configs:
                      - role: node
                  - job_name: 'kubernetes-pods'
                    kubernetes_sd_configs:
                      - role: pod
                    relabel_configs:
                      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                        action: keep
                        regex: true
                      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                        action: replace
                        target_label: __metrics_path__
                        regex: (.+)
                      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                        action: replace
                        regex: (.+):(?:\d+);(\d+)
                        replacement: $1:$2
                        target_label: __address__
          exporters:
            prometheusremotewrite:
              endpoint: "http://vmsingle-victoria-metrics-single-server.monitoring.svc:8428/api/v1/write"
          service:
            pipelines:
              metrics:
                receivers: [prometheus]
                exporters: [prometheusremotewrite]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
