apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-kube-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-kube-stack
    targetRevision: 0.7.0
    helm:
      releaseName: otel-kube
      values: |
        mode: deployment
        clusterName: dev-cluster
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        opentelemetry-operator:
          admissionWebhooks:
            certManager:
              enabled: false
            autoGenerateCert:
              enabled: true
        receivers:
          prometheus:
            config:
              scrape_configs:
                - job_name: kubernetes-pods
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - source_labels: [__meta_kubernetes_pod_label_app]
                      target_label: job
                    - source_labels: [__address__]
                      target_label: instance
        exporters:
          prometheusremotewrite:
            endpoint: "http://vmsingle-victoria-metrics-single-server.monitoring.svc:8428/api/v1/write"
        collector:
          enabled: true
        components:
          kubeletstats:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
