apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-
spec:
  serviceAccountName: argo-workflows # this is the service account that the workflow will run with
  entrypoint: main # the first template to run in the workflows
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: echo
            onExit: tidy-up
    - name: echo
      container:
        image: busybox
        command: [echo]
        args: ["hello world"]
    - name: tidy-up
      container:
        image: busybox
        command: [echo]
        args: ["tidy up!"]