apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-parameters-
spec:
  serviceAccountName: argo-workflows # this is the service account that the workflow will run with
  entrypoint: main # the first template to run in the workflows
  templates:
      - name: main
        dag:
          tasks:
            - name: generate-parameter
              template: echo
            - name: consume-parameter
              template: print-message
              dependencies:
                - generate-parameter
              arguments:
                parameters:
                  - name: message
                    value: "{{tasks.generate-parameter.outputs.parameters.hello-param}}"

      - name: echo
        container:
          image: busybox
          command: [sh, -c]
          args: ["echo -n hello world > /tmp/hello_world.txt"]
        outputs:
          parameters:
            - name: hello-param
              valueFrom:
                path: /tmp/hello_world.txt

      - name: print-message
        inputs:
          parameters:
            - name: message
        container:
          image: busybox
          command: [echo]
          args: ["{{inputs.parameters.message}}"]