apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.16 # or 'latest' — check https://artifacthub.io/packages/helm/argo/argo-rollouts
    helm:
      releaseName: argo-events
      values: |
        controller:
          replicas: 1
        eventBus:
          nats:
            native:
              replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true