---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-access
  namespace: argo-workflows
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates", "workflows", "workflowtaskresults", "ClusterWorkflowTemplate"]
    verbs: ["get", "list", "watch", "create", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-workflow-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: Role
  name: workflow-access
  apiGroup: rbac.authorization.k8s.io