---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcreds
  namespace: argo-events
spec:
  encryptedData:
    .dockerconfigjson: AgByutOA0stWDwymeNHViSv7J8vf97IMXzFszFylmGInBCNutmtBWU2dLvSkzmozLFCFNAky2OnheMMe4ECynSlHB+0fze5M7bNZf6PV6g13f5WkvQFN5ql3GEGEPdiN3qxvrY5dFusBHwbijuNQ2Zmei9w6WVYI08LnDmS1a/Df+XbF6kGiDcq+t5cnYXXhhKHVh5yzMx1QhI/drLfIkK4yxkEkuiNhpx2cO2Vmw+6IzKj0vt66DBXaot/pvm1tJ9R96A4d+4TAY26xEzCKoPsY/oy3pPKMUtgSjVJmaPu3anQAFkAePLx17A3714e/b98MgWQnbjAzpcRJSf7BfdDrUdvc4HkqenP7Z7MPipVYjJkaahgDtdDfqUxdrv5qt9NAXp0m/ffgWSvjEg0eceTjd0X7Fh3AHsKH8Pd0mk8BD7OS1I0HEe/Isdi+dh7v6+RHjDT6u9+T0ITi5wMlnrFJ6vqiCSm/qLdlDsQfmNidacvE+K/GXLxHAhqginQj0kc0g278xKyXSDPI2V9MvJC3XZSNiI6j598jR16FTJCXNMhY7pXJNXZu0Duo3KM5JM0/McCqlsU9DNd85HFn8faeRdg2oBM8RWfoeUF5OtsrriCmV1x3LTg6oC9sI+LUT1S/KbeWGXwMaYQO0Dhq8J3pZGeCZEbPNIVJ013x2tlGP5Ev6f+54gq+DuVn5Vr52ebf7nZhRmlCeKHi0x5Jiwvb6JssL0s9aQchhBCrIel/Q419IYV76ikL5JnO7KoZoeDqhcAwb5NiICiUalGL/esFaYPBhXFdxE9ABMr62sNaalco3wHQ7Tdq4S3BZVI9yqpmhLLZFSD/nF3s1wXcvCBCeNlUdoSbXMZXT6xO/o6M4mSEHe6jaD4n5rKdSY6O8pek1hXeJ/NqI9tz9tZGVLM7s0QR9Z+HKguZ/gyq7mlKHsEe
  template:
    metadata:
      creationTimestamp: null
      name: regcreds
      namespace: argo-events
    type: kubernetes.io/dockerconfigjson