---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: argo-events

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-access
  namespace: argo-events
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates", "workflows"]
    verbs: ["get", "list", "watch", "create"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-workflow-binding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
    namespace: argo-events
roleRef:
  kind: Role
  name: workflow-access
  apiGroup: rbac.authorization.k8s.io