apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: docker-ci-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: repo-dep
      eventSourceName: webhook
      eventName: repo-events
  triggers:
    - template:
        name: docker-ci-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: docker-ci-
                namespace: argo-workflows
              spec:
                workflowTemplateRef:
                  name: docker-ci-pipeline
                arguments:
                  parameters:
                    - name: repoUrl
                      # value: "{{events.webhook.repo-dep.payload.repoUrl}}"
                      value: REPOURL
                    - name: imageName
                      # value: "{{events.webhook.repo-dep.payload.imageName}}"
                      value: IMAGENAME
                    - name: imageTag
                      # value: "{{events.webhook.repo-dep.payload.imageTag}}"
                      value: IMAGETAG
                    - name: dockerfile
                      value: DOKERFILE
                      # value: "{{events.webhook.repo-dep.payload.dockerfile}}"
          parameters:
            - src:
                dependencyName: repo-dep
                dataKey: body.repoUrl
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: repo-dep
                dataKey: body.imageName
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: repo-dep
                dataKey: body.imageTag
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: repo-dep
                dataKey: body.dockerfile
              dest: spec.arguments.parameters.3.value