apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: argo-events
spec:
  entrypoint: main
  ttlStrategy:
    secondsAfterCompletion: 60
  templates:
    - name: main
      container:
        image: alpine:3.17
        command: ["sh", "-c"]
        args: ["echo 'Hello from Argo Events 🚀'"]
