gateway:
  name: my-app-gateway
  namespace: default
  selector:
    istio: ingressgateway
  port: 80
  hosts:
    - "*"

virtualService:
  name: my-app-vs
  namespace: default
  gateway: my-app-gateway
  hosts:
    - "*"
  prefix: /
  destination:
    host: my-app-service
    port: 80