gateway:
  name: ingress-gw
  namespace: istio-system
  selector:
    istio: ingressgateway
  port: 80
  hosts:
    - "*"

virtualService:
  name: ingress-vs
  namespace: istio-system
  gateway: ingress-gw
  hosts: 
    - ""
  http:
    - match:
      - uri:
          prefix: /argocd
      rewrite:
        uri: /
      route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port: 
              number: 80
