image:
  backend:
    repository: docker.io/REPLACE_ME/devhub-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/REPLACE_ME/devhub-frontend
    tag: latest
    pullPolicy: IfNotPresent
service:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: ClusterIP
    port: 80
mongo:
  uri: mongodb://root:root@mongodb.mongodb.svc.cluster.local:27017/?authSource=admin
  db: devhub
  collection: orders
ingress:
  enabled: false
  className: ""
  hosts:
    - host: devhub.local
      paths:
        - path: /
          pathType: Prefix
