backend:
  strategy: rollout
  image:
    repository: docker.io/victor1721swed/cellit-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000

frontend:
  strategy: rollout
  image:
    repository: docker.io/victor1721swed/cellit-frontend
    tag: v2.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

mongo:
  uri: mongodb://root:root@mongodb-headless.mongodb.svc.cluster.local:27017/?authSource=admin&replicaSet=rs0
  db: devhub
  collection: orders

