image:
  backend:
    repository: docker.io/victor1721swed/cellit-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: docker.io/victor1721swed/cellit-frontend
    tag: latest
    pullPolicy: IfNotPresent
service:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: ClusterIP
    port: 80
mongo:
  uri: mongodb://root:root@mongodb.mongodb.svc.cluster.local:27017/?authSource=admin
  db: devhub
  collection: orders

