apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
  {{- toYaml .Values.virtualService.http | nindent 4 }}