{{- range .Values.virtualServices }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  hosts:
    {{- toYaml .hosts | nindent 4 }}
  gateways:
    - {{ .gateway }}
  http:
  {{- toYaml .http | nindent 4 }}
{{- end }}
